In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
bRet1 = False
file_list_clean = os.listdir('H:/crawl and extract/extract/train/train_path')
path = 'H:/crawl and extract/extract/train/train_path/'
for b in range(len(file_list_clean)):
    data = pd.read_csv(path+str(b)+'.csv',encoding= 'unicode_escape',sep=',',
                       names=["0", "1", "2", "3", "4","5","6","7","8","9","10","11", "12", "13", "14","15","16","17","18","19","20","21", "22", "23", "24","25","26","27","28","29","30"]
                      )
    if bRet1 == False:
        data_clean = data
        bRet1 =True
    else:    
        data_clean = data_clean.append(data,ignore_index=True)

In [3]:
data_clean

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,30
0,1.462455,125,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,1.363937,125,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,1.521981,125,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,1.547260,125,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,1.555878,125,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7096,1.577525,125,0,0,0,3,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7097,1.563490,125,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7098,1.590138,125,0,0,0,3,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7099,1.587355,125,0,0,0,3,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7100,1.590187,125,0,0,0,3,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
X_train = data_clean[["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29"]]
y_train = data_clean["30"]

In [5]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_jobs=2, random_state=0)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=2,
                       oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [6]:
clf.score(X_train, y_train)

1.0

In [18]:
clf.predict([[1.462455,125,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]])

array([1], dtype=int64)

In [23]:
file_test = pd.read_csv('H:/crawl and extract/extract/test_save/clean/data_sach_779_080420.csv')
file_test

,1.392351,125,0,0.1,0.2,1,0.3,0.4,0.5,0.6,...,0.17,0.18,0.19,0.20,0.21,0.22,0.23,0.24,0.25,0.26
0,0.456162,59,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0.456162,59,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0.456162,59,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0.456162,59,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0.456162,59,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
773,1.628152,125,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
774,0.456162,59,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
775,1.489390,125,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
776,0.456162,59,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
777,1.589788,125,0,0,0,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [24]:
X_test = file_test.iloc[:, 0:30].values
y_test = file_test.iloc[:, 30].values

In [25]:
clf.score(X_test, y_test)

0.9485861182519281

In [41]:
import pickle
filename = 'finalized_model.sav'
pickle.dump(clf, open(filename, 'wb'))